import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "BD Telecom Money Receipt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-verdana antialiased">
        {children}
      </body>
    </html>
  );
}
